# Generated by Django 5.0.2 on 2024-03-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_bio_remove_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Não definido'), (1, 'Homen'), (2, 'Mulher'), (3, 'Outro')]),
        ),
    ]
